/**
 * Writes the brand SVGs in assets/brand: the app's cycle ring (28 days, 5 bleeding days, the
 * engine's phase split) in the 1c Intim phase colours, with the heart in the menstrual colour.
 *   node scripts/brand-svg.mjs && node scripts/render-brand.mjs
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const COLOURS = {
  light: {
    men: '#B04D59',
    fol: '#218373',
    ovu: '#AA732B',
    lut: '#725CA9',
    bg: '#EEE8EB',
    text: '#1D161B',
  },
  dark: {
    men: '#EC8A92',
    fol: '#6BC4B3',
    ovu: '#E7B369',
    lut: '#AA95E8',
    bg: '#0D0A0E',
    text: '#F2EAEE',
  },
};
const GLYPH = { r: 300, width: 64, gap: 3.6, heartScale: 0.88 };
const ICON = { r: 330, width: 70, gap: 3.8, heartScale: 1.0 };
const HEART =
  'M 0 118 C -30 92 -128 32 -128 -46 C -128 -100 -86 -132 -46 -132 C -20 -132 -6 -118 0 -106 C 6 -118 20 -132 46 -132 C 86 -132 128 -100 128 -46 C 128 32 30 92 0 118 Z';

const polar = (r, a) => {
  const t = ((a - 90) * Math.PI) / 180;
  return [r * Math.cos(t), r * Math.sin(t)];
};
const f = (n) => n.toFixed(2);
const arc = (r, s, e) => {
  const [x1, y1] = polar(r, s);
  const [x2, y2] = polar(r, e);
  return `M ${f(x1)} ${f(y1)} A ${r} ${r} 0 ${e - s > 180 ? 1 : 0} 1 ${f(x2)} ${f(y2)}`;
};
const phaseFor = (d) => (d <= 5 ? 'men' : d <= 12 ? 'fol' : d <= 15 ? 'ovu' : 'lut');

function segments(c, { r, gap }) {
  let out = '';
  for (let d = 1; d <= 28; d++) {
    const s = ((d - 1) * 360) / 28 + gap / 2;
    const e = (d * 360) / 28 - gap / 2;
    out += `    <path d="${arc(r, s, e)}" stroke="${c[phaseFor(d)]}"/>\n`;
  }
  return out;
}

const head = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <!-- Generated by scripts/brand-svg.mjs: the app's cycle ring in the 1c Intim phase colours. -->
`;
const ring = (c, g) =>
  `  <g transform="translate(512 512)" fill="none" stroke-width="${g.width}">\n${segments(c, g)}  </g>\n`;
const heart = (c, scale, y) =>
  `  <g transform="translate(512 ${y}) scale(${scale})">\n    <path d="${HEART}" fill="${c.men}"/>\n  </g>\n`;

const glyph = (c) => head + ring(c, GLYPH) + heart(c, GLYPH.heartScale, 528) + '</svg>\n';

/** The splash: the glyph raised, with the app name in Manrope Light under it (font loaded by render-brand.mjs). */
const splash = (c) =>
  head +
  `  <g transform="translate(0 -92)">\n` +
  ring(c, GLYPH) +
  heart(c, GLYPH.heartScale, 528) +
  `  </g>\n` +
  `  <text x="512" y="905" text-anchor="middle" font-family="Manrope" font-weight="300" font-size="108" letter-spacing="-1" fill="${c.text}">Cycle Tracker</text>\n` +
  '</svg>\n';
const icon = (c) =>
  head +
  `  <rect width="1024" height="1024" fill="${c.bg}"/>\n` +
  ring(c, ICON) +
  heart(c, ICON.heartScale, 530) +
  '</svg>\n';

/** The splash split in layers for the in-app handover: the ring alone and the heart alone, in the splash's frame. */
const splashRing = (c) =>
  head + `  <g transform="translate(0 -92)">\n` + ring(c, GLYPH) + `  </g>\n</svg>\n`;
const splashHeart = (c) =>
  head +
  `  <g transform="translate(0 -92)">\n` +
  heart(c, GLYPH.heartScale, 528) +
  `  </g>\n</svg>\n`;

const splashText = (c) =>
  head +
  `  <text x="512" y="905" text-anchor="middle" font-family="Manrope" font-weight="300" font-size="108" letter-spacing="-1" fill="${c.text}">Cycle Tracker</text>\n` +
  '</svg>\n';

const out = (name, svg) => writeFileSync(resolve(root, 'assets/brand', name), svg);
out('glyph.svg', glyph(COLOURS.light));
out('glyph-dark.svg', glyph(COLOURS.dark));
out('splash.svg', splash(COLOURS.light));
out('splash-dark.svg', splash(COLOURS.dark));
out('splash-ring.svg', splashRing(COLOURS.light));
out('splash-ring-dark.svg', splashRing(COLOURS.dark));
out('splash-heart.svg', splashHeart(COLOURS.light));
out('splash-heart-dark.svg', splashHeart(COLOURS.dark));
out('splash-text.svg', splashText(COLOURS.light));
out('splash-text-dark.svg', splashText(COLOURS.dark));
out('icon.svg', icon(COLOURS.light));
out('icon-dark.svg', icon(COLOURS.dark));
console.log('wrote assets/brand/*.svg');
